name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull the docker image
      run: sudo docker pull rajeshjallu/cicd-pipeline:latest
    - name: Delete the old Docker conatiner
      run: sudo docker rm cicd-container || true
    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name cicd-container rajeshjallu/cicd-pipeline
